apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadfpma7037-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadfpma7037-tenant-component
    app.kubernetes.io/part-of: loadfpma7037-tenant-app
  name: loadfpma7037-tenant-component
  namespace: loadfpma7037-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadfpma7037-tenant-component
    weight: null
status: {}
